### ISSUE TITLE
AttributeError: 'module' object has no attribute 'WebSocketClientProtocol'

### ISSUE THREAD

**Issue by icyrockcom** [jvansteirteghem/twunnel#1]
Running `example3.py`:

```
Traceback (most recent call last):
  File "example3.py", line 7, in <module>
    from twunnel import local_proxy_server, logger, proxy_server, remote_proxy_server
  File "/home/icyrockcom/.virtualenvs/default/local/lib/python2.7/site-packages/twunnel/local_proxy_server.py", line 1010, in <module>
    class WSOutputProtocol(autobahn.websocket.WebSocketClientProtocol):
AttributeError: 'module' object has no attribute 'WebSocketClientProtocol'
```

As per [AutobahnPython](https://github.com/tavendo/AutobahnPython#upgrading-from-autobahn--070) note, the package changed in v0.7.0 to support multiple backends from `autobahn.websocket` to `autobahn.twisted.websocket` (for Twisted backend).

**Comment by jvansteirteghem** [comment]
I have updated twunnel: twunnel 0.8.1 now requires autobahn>=0.7.0.
Thank you for your help!

**Comment by icyrockcom** [comment]
Great, thanks for a quick response!
